### ISSUE TITLE
Build fails with 'The term ""hd: empty list"" has type "string" while it is expected to have type "bytestring.string".'

### ISSUE THREAD

**Issue by haansn08** [uds-psl/coq-library-undecidability#162]
It seems the building from source breaks when compiling with a [recent version](https://github.com/MetaCoq/metacoq/commit/64bdee825cf1324e2f0b4a5f41643262fd07b201) of MetaCoq. I run into following errors when running `make`:

```
COQC L/Tactics/Extract.v
File "./L/Tactics/Extract.v", line 2, characters 0-58:
Error: Notation "_ == _" is already defined at level 50 with arguments constr
at next level, constr at next level while it is now required to be
at level 70 with arguments constr at next level, constr at next level.
```

This can be remedied by setting the `==` notation in `L/Util/L_facts.v` to level 70:
```diff
diff --git a/theories/L/Util/L_facts.v b/theories/L/Util/L_facts.v
index a8c5240..e8e8be1 100644
--- a/theories/L/Util/L_facts.v
+++ b/theories/L/Util/L_facts.v
@@ -386,7 +386,7 @@ Qed.
 
 (* Equivalence *)
 
-Reserved Notation "s '==' t" (at level 50).
+Reserved Notation "s '==' t" (at level 70).
 
 Inductive equiv : term -> term -> Prop :=
   | eqStep s t : step s t -> s == t
```
However I still get errors relating to the required string implementation in the same file which I could not yet fix easily:
```
COQC L/Tactics/Extract.v
File "./L/Tactics/Extract.v", line 53, characters 18-34:
Error:
In environment
X : Type
l : list X
The term ""hd: empty list"" has type "string"
while it is expected to have type "bytestring.string".
```

**Comment by DmxLarchey** [comment]
I ran into a similar problem yesterday: `bytestring`/`MetaCoq` warnings. The `opam` file changed in a recent [commit cc35e6cc11730680db3ad306538d119b4d3fe51f](https://github.com/uds-psl/coq-library-undecidability/commit/cc35e6cc11730680db3ad306538d119b4d3fe51f). Please check your version of `coq-metacoq-template` is  `1.0+8.15` and not `dev+8.15`.

**Comment by DmxLarchey** [comment]
Is the issue resolved ?

**Comment by haansn08** [comment]
> Is the issue resolved ?

Yes. I now realized I cloned an old version of this repository because `uds-psl/coq-library-complexity` includes `fakusb/coq-library-undecidability` as a submodule and not `uds-psl/coq-library-undecidability`.
