### ISSUE TITLE
Integration of First-Order Logic

### ISSUE THREAD

**Issue by dominik-kirst** [uds-psl/coq-library-undecidability#177]
Now that the [library on first-order logic](https://github.com/dominik-kirst/coq-library-undecidability/tree/fol-library/theories/FOL) is nearly complete, I guess it's time we discuss a plan for the integration with the undecidability library. Currently, we have just merged all developments into a reorganised FOL folder in my fork of the undecidability library. The Undecidability subfolder is still in the same organisation as used in the undecidability library. This leaves three options how we could proceed:

- We file a PR as is, from preliminary discussions this seems to be the worst option.
- We split the FOL library into the core and undec parts to be included in the undec library and have a dependency of the remaining FOL library on the undec library.
- We have a mostly self-contained FOL library with the undec parts in the undec library then depending on it.
- We compose a self-contained FOL core library that both the undec and full FOL library depend on.

What is your opinion? Would it maybe make sense to have a Zoom call once Yannick is back from his holidays? I could also elaborate on these options first and try to estimate how much of the contents would go into which sub-library first, if that is of any help :)

**Comment by yforster** [comment]
Happy to do a zoom call anytime now. Ping for @DmxLarchey and @mrhaandi. From the perspective of the undecidability library, (2) seems to be best for me.

**Comment by mrhaandi** [comment]
> We split the FOL library into the core and undec parts to be included in the undec library and have a dependency of the remaining FOL library on the undec library.

This option (2) seems best to me.

**Comment by DmxLarchey** [comment]
Option (2) seems also best to me but that is the point of view of the lazy maintainer of the undec library, ie for us it is best not to depend on an external library. Option (4) could be discussed in case a very stable core could be designed AND maintained over the long run.

**Comment by dominik-kirst** [comment]
I have info from @yforster and @mrhaandi that 5pm would work instead of 3pm, is that fine for @DmxLarchey as well? :)

**Comment by dominik-kirst** [comment]
> Ok I will do it from home them. See you.

Perfect, sorry for the short notice!

**Comment by dominik-kirst** [comment]
> Is this your personal Zoom chat room ?

Yep :)

**Comment by dominik-kirst** [comment]
Quick summary of the call yesterday for future reference:

- We go with variant (2), meaning the core folders (mostly Syntax, Semantics, Deduction) remain in the undec library, the rest will become the FOL library.
- The FOL library will have dummy files pointing to the corresponding files in the undec library to ease imports.
- The Undecidability folder will be brought one level up to comply with the other folders in the undec library.
- The TRAKHTENBROT folder will become a subfolder of the FOL folder.
- The file contributed to the undec library will be checked to have no dependencies on external libraries and to be easy to maintain.
- The enumerability of mu programs will move to a better place, probably the MuRec folder.

Just let me know if I forgot something :)
