### ISSUE TITLE
master CI fails with "/usr/bin/git ls-files" exited with code 128

### ISSUE THREAD

**Issue by mrhaandi** [uds-psl/coq-library-undecidability#193]
@yforster 
On `Install dependencies`, `opam install --confirm-level=unsafe-yes -j 2 . --deps-only`:
```
Error:  Command "/usr/bin/git ls-files" failed:
  "/usr/bin/git ls-files" exited with code 128
```

**Comment by yforster** [comment]
We had the same problem in MetaCoq. The fix is already mentioned in the Coq 
docker repo: run the chown in before-install instead of before-script. I 
can port the fix here es well.

**Comment by yforster** [comment]
I accidentally pushed directly to the `master` branch rather than doing a PR, but I think the fix is working.
