### ISSUE TITLE
library 1.0.0+8.12 opam release

### ISSUE THREAD

**Issue by mrhaandi** [uds-psl/coq-library-undecidability#81]
Here is a wish list for the upcoming opam release of the undecidability library version `1.0.0+8.12` (we'll try to hit 20.11.)
@yforster @fakusb @DmxLarchey 
- [x] remove `PslBase` dependency
- [x] refactor/remove `Shared.Prelim`
- [x] compiles with coq 8.12.1
- [x] cleanup output ~~(what is all the `phi1 = ∀ Pred (!P) (Vector.cons (var 0) (Vector.cons (var 0) Vector.nil)) : form` and `prv_class is not universe polymorphic` output?)~~
- [x] fix warnings ~~(I get `Warning: Notation "_ [ _ ]" was already defined with a different format` and `Warning: Not a truly recursive fixpoint.`)~~ ~~By the way, why are those not shown in the CI logs?~~
- [x] move the final FOL files away from `Problems` and `Reductions` ~~(no need to fully clean up FOL now)~~
- [x] paper-ready System F presentation
- [x] Hoare framework rework (I'm not sure about his one, @fakusb knows more)
- [x] cleaner, modular, commented synthetic definitions. Our agreed focus are non-informative reductions. ~~I do not expect (exposed!) notation definitions such as `"⪯ᵢ"` in `ReducibilityFacts.v` that is included everywhere.~~
- [x] remove uncompiled files
- [x] more uniform FOL

By the way, the suggested version `X.Y.Z+A` is:
- `X` increases on major design changes
- `Y` increases on new undecidability results
- `Z` increases on minor improvements
- `A` is the Coq version used

**Comment by yforster** [comment]
I'll fix the CI logs, can take care of the FOL stuff, repair the subst notation and will clean up the output regarding FOL. The fixpoint warning probably has to stay, but we can add it to the ignored warnings in CoqProject.

**Comment by mrhaandi** [comment]
> The fixpoint warning probably has to stay

In both cases the fixpoint warnings could be fixed by 
```
Definition de_bruijn_ext {X : Type} := 
  fix de_bruijn_ext (ν : nat -> X) (x : X) (n : nat) {struct n} : X :=
    match n with
    | 0 => x
    | S n => ν n
    end.
```

In general, I'm against disabling any warnings (even unfixable ones). If warnings completely pollute the output, then clearly the problem lies elsewhere.

**Comment by yforster** [comment]
Is this in the H10 part? My comment assumed that the problem occurs in the L directory.

**Comment by DmxLarchey** [comment]
I know that I used `Fixpoint` instead of `Definition` for the definition of De Bruijn extensions for better default unfolding behavior wrt. to the `simpl` tactic. This occurs for sure in Trahktenbrot and if I remember well, also in H10. Of course this is a warning about a perfectly legitimate use of `Fixpoint`.

I will see if _local fixpoints_ improve things wrt to warnings while respecting the good unfolding properties and if so, I will switch them to `Definition foo := fix foo ...`

**Comment by yforster** [comment]
If I understand correctly, Andrej fixed both occurrences already, right @mrhaandi?

**Comment by mrhaandi** [comment]
> If I understand correctly, Andrej fixed both occurrences already, right @mrhaandi?

The fixes will not be part of my System F PR. I just checked that the fix is very easy and can be done as part of a Warning cleanup PR (for better separation of concerns).

**Comment by mrhaandi** [comment]
@DmxLarchey By the way, why is controlling unfolding behavior via `Fixpoint` superior to `Arguments`? I usually use the latter.

**Comment by fakusb** [comment]
Not sure why @DmxLarchey uses it, but Fixpoint unfolding control is guaranteed by the kernel and even enforced during coercion, while arguments is merely respected by smpl/cbn.

**Comment by DmxLarchey** [comment]
@mrhaandi Laziness? No seriously I have been struggling a lot with `Arguments` over time while `Fixpoint` almost never disappoints me ... and @fakusb just gave the correct answer here !!

**Comment by mrhaandi** [comment]
> @fakusb just gave the correct answer here !!

I see. Well, in the cases at hand (as above alternatives show) `Fixpoint` (and also `Arguments`) are not necessary. So, I'm still in favor of code without warnings.

**Comment by fakusb** [comment]
A related tip: In addition to `Arguments "+" : simpl never.`, one can tell coq to delay unfolding functions during conversion/unification by using the Strategy command, a more fine-grained interface to `Transparent`/`Opaque`: https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:cmd.strategy
For example, `Strategy 1000 ["+"].` would tell coq to delay unfolsing "+" until it is absolutely necessary.

**Comment by yforster** [comment]
I have the following TODOs for the opam release:

- add `TSR_undec` proof
- merge #72 after adding proofs regarding natural numbers
- take care of #49

**Comment by yforster** [comment]
@dominik-kirst Can we hope for a new `FOL` directory until Friday, getting rid of the explicit names?

**Comment by dominik-kirst** [comment]
Including or excluding Friday? I'm currently working on it, but seems I need to fix more things than expected...

**Comment by yforster** [comment]
If we file a PR against the Coq opam repo on Friday evening I'm happy. 
@mrhaandi is that also okay for you?

**Comment by mrhaandi** [comment]
> If we file a PR against the Coq opam repo on Friday evening I'm happy.

Me too (let's say before 20:00).

**Comment by yforster** [comment]
Once #97 is merged I'll package a release and file a PR against the `coq-released` repo.

**Comment by yforster** [comment]
https://github.com/coq/opam-coq-archive/pull/1477

`opam update && opam info coq-library-undecidability` should now list our library in two versions (one is the release, the other is just installing from the current head of the `8.12` branch).
